### ISSUE TITLE
PageTemplate.tsx  수정이 필요 할 것 같습니다.

### ISSUE THREAD

**Issue by doggopawer** [kmyobin/Can_I_Eat#5]
### 📝Description
레이아웃 width가 1280px로 고정되지 않아 아래와 같은 문제가 발생합니다.
틀린것은 아니지만, 보통 아래와 같은 형식으로 컨텐트 width는 고정하는걸로 알고 있습니다.

Header와, Content 부분의 width 값을 1280px로 고정하고, margin : 0 auto 값으로 가운데 정렬이 필요할 것 같습니다.

### Screenshots
<img width="1440" alt="스크린샷 2023-04-13 오후 5 10 40" src="https://user-images.githubusercontent.com/107387817/231697265-46dc76d6-6053-4b45-8667-1aa7c5080801.png">

<img width="1439" alt="스크린샷 2023-04-13 오후 5 10 21" src="https://user-images.githubusercontent.com/107387817/231697492-767db9cc-f11f-4bca-b3ea-c803c33d3db0.png">

**Comment by kmyobin** [comment]
제 노트북이 15.6인치?인데 1280px로 하면 넘치더라구요. 그래서 content width는 1040px로 고정헸습니다. 모바일은 폰 화면 크기 구성이 다양하기도 하고 화면의 모든 부분을 사용하는게 좋을 것 같아 width를 100%로 설정하였습니다.
